#+title: Readel
#+author: EFLS
#+date: 2024

Readel is a basic retrieval system for Readeck annotations. It will
show or insert highlights (called "annotations" in Readeck) from a
selected article (called "bookmark") in Org-mode formatting.

Readeck is a self-hosted read-it-later system. See [[https://readeck.org][readeck.org]].

To use Readel, set the following parameters:

#+begin_src emacs-lisp
(setq readel-url "https://url.to.readeck"  ;; Readeck URL
      readel-token "abc123"                ;; Readeck API token
      readel-bookmarks-label "label")      ;; Label to filter bookmarks
#+end_src

Note:
 - Set =readel-bookmarks-label= to nil to disable filtering of
   bookmarks.
 - Make sure there is no trailing =/= in the =readel-url=.

Readel will retrieve and show highlights in Org-mode formatting.

Readel provides two user-facing functions:
- =readel-annotations-insert-from-bm= to select a bookmark and display
  its annotations in a separate buffer.
- =readel-annotations-buffer-render= to select a bookmark and insert its
  annotations at point.

Note: The code is very basic. Data is stored in alists as retrieved
from the server. The =request= code will wait until requests are
completed. There's no error handling involved.

But it does allow me to quickly get highlights from articles I've
saved into and read on Readeck, which is pretty useful.

Similar (but much more elaborate) projects for different types of
read-it-later services:
- [[https://github.com/Kungsgeten/hypothesis][Hypothesis.el]] for annotations on hypothes.is. I have used this for a long time, it's amazing to use when you annotate with [[https://hypothes.is/]].
- [[https://github.com/karthink/wombag][Wombag]] and [[https://github.com/chenyanming/wallabag.el][Wallabag.el]] for (much more extensive) integration with
  Wallabag. I really like Wombag, as it uses the elfeed interface to
  interact with stored articles.

